// Shared definitions for the DRscore cross-account scanner role.
// Used by both the "Connect AWS Account" UI (to render the policy/CFN
// template) and, from Phase 2 onward, the scan backend.

export const SCANNER_ROLE_NAME = "DRscoreScannerRole";
export const DEFAULT_REGION = "us-east-1";
export const AWS_ACCOUNT_ID_RE = /^\d{12}$/;

// Least-privilege, read-only actions needed by the Phase 1 checks
// (backup, RDS multi-AZ, EC2/EBS snapshots) plus the remaining Phase 4
// categories. Intentionally narrower than the AWS-managed ReadOnlyAccess
// policy.
export const SCANNER_POLICY_DOCUMENT = {
  Version: "2012-10-17",
  Statement: [
    {
      Sid: "DRscoreReadOnly",
      Effect: "Allow",
      Action: [
        "backup:List*",
        "backup:Describe*",
        "rds:DescribeDBInstances",
        "rds:DescribeGlobalClusters",
        "rds:DescribeDBClusters",
        "ec2:DescribeSnapshots",
        "ec2:DescribeVolumes",
        "ec2:DescribeInstances",
        "s3:GetBucketReplication",
        "s3:ListAllMyBuckets",
        "s3:GetBucketLocation",
        "route53:ListHealthChecks",
        "route53:ListHostedZones",
        "route53:ListResourceRecordSets",
        "dynamodb:DescribeTable",
        "dynamodb:ListTables",
        "resiliencehub:ListApps",
        "resiliencehub:DescribeResiliencyPolicy",
        "sts:GetCallerIdentity",
      ],
      Resource: "*",
    },
  ],
} as const;

export function buildTrustPolicy(scannerAccountArn: string, externalId: string) {
  return {
    Version: "2012-10-17",
    Statement: [
      {
        Effect: "Allow",
        Principal: { AWS: scannerAccountArn },
        Action: "sts:AssumeRole",
        Condition: {
          StringEquals: { "sts:ExternalId": externalId },
        },
      },
    ],
  };
}

export function buildRoleArn(awsAccountId: string, roleName: string = SCANNER_ROLE_NAME): string {
  return `arn:aws:iam::${awsAccountId}:role/${roleName}`;
}

// One-click CloudFormation template that creates the scanner role with the
// correct trust policy (scoped to this connection's ExternalId) and the
// least-privilege permissions policy attached inline.
export function buildCloudFormationTemplate(scannerAccountArn: string, externalId: string): string {
  // Must be indented to at least the "Action:" key's own column (16 spaces
  // below), or the YAML parser dedents out of the enclosing statement map.
  const policyActions = SCANNER_POLICY_DOCUMENT.Statement[0].Action.map((a) => `                  - "${a}"`).join("\n");
  return `AWSTemplateFormatVersion: "2010-09-09"
Description: DRscore read-only cross-account scanner role

Parameters:
  ExternalId:
    Type: String
    Default: "${externalId}"
    Description: Unique ID generated by DRscore for this connection. Do not share.
  ScannerAccountArn:
    Type: String
    Default: "${scannerAccountArn}"
    Description: DRscore's scanner identity, allowed to assume this role.

Resources:
  DRscoreScannerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${SCANNER_ROLE_NAME}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref ScannerAccountArn
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref ExternalId
      Policies:
        - PolicyName: DRscoreReadOnly
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: DRscoreReadOnly
                Effect: Allow
                Action:
${policyActions}
                Resource: "*"

Outputs:
  RoleArn:
    Description: Paste this back into DRscore if it isn't auto-detected.
    Value: !GetAtt DRscoreScannerRole.Arn
`;
}
